/* eslint-disable check-file/filename-naming-convention */

import { useState } from 'react';

import Head from 'next/head';
import Link from 'next/link';

import styles from 'app/styles/Home.module.css';

function Home({ }) {
  const [user, setUser] = useState('ndr');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h4>LANDING</h4>
        <div style={{ display: 'inline-block' }}>
          <span style={{ marginRight: 5 }}>User</span>
          <select onChange={(e) => setUser(e.target.value)} style={{ marginRight: 5 }}>
            {/* <option value=''><em>None</em></option> */}
            <option value='ndr'>ndr</option>
            <option value='xixixviii'>xixixviii</option>
            <option value='Lisundawu'>Lisundawu</option>
            <option value='Nadifa'>Nadifa</option>
          </select>
          <Link href={`/user/${user}`}>
            <button>Go To User Page</button>
          </Link>
        </div>
        <Link href={'/todos'}>
          <button className={styles.link}>Go To SSR Page <br />with Image Optimization from Next Js</button>
        </Link>
        <Link href={'/todo-get-api-next'}>
          <button className={styles.link}>Go To SSR Page<br /> With Get API from Local Next Js</button>
        </Link>
        <Link href={'/todo-ssg'}>
          <button className={styles.link}>Go To SSG Page</button>
        </Link>
        <Link href={'/todo-csr'}>
          <button className={styles.link}>Go To CSR Page with React-Query <br /> with signal cancellation</button>
        </Link>
        <Link href={'/todo-csr-no-rq'}>
          <button className={styles.link}>Go To CSR Page without React-Query <br /> with Image Optimization from Next Js</button>
        </Link>
      </main>
    </>
  );
};

Home.getInitialProps = async () => {
  return {
    props: {}
  };
};

export default Home;
