/* eslint-disable check-file/filename-naming-convention */

import { useState } from 'react';

import Head from 'next/head';
import Link from 'next/link';

import HomePage from 'app/common/container/home/index';

import styles from 'app/styles/Home.module.css';

function Home({ }) {
  const [user, setUser] = useState('ndr');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </>
  );
};

Home.getInitialProps = async () => {
  return {
    props: {}
  };
};

export default Home;
